title:Krutika Hampannavar
description:>
Application Development Analyst | Ex- Accenture
<br><br>
<a href="mailto:krutikahampannavar@gmail.com">krutikahampannavar@gmail.com</a>
<br>
<a href="https://www.linkedin.com/in/krutikahampannavar/">LinkedIn Profile</a>
<br>
<a href="https://www.github.com/GIT12Krutika/">Github</a>
theme: jekyll-theme-minimal
